### ISSUE TITLE
Creating a Kanban board

### ISSUE THREAD

**Issue by digia3d** [digia3d/Cook-Book#13]
In this project, there are two people: @Said and @digia3d.
Link for our project: https://github.com/users/digia3d/projects/5.

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @digia3d and @Said-laasri,

Good job so far!
✔️ Kanban columns are correctly set up
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] These two tasks do not have descriptions. Kindly fix that. For the first one, I think the issue titled: "Create Login and Registration Page" takes care of that so it is repetitive and can be removed.

  ![digi](https://user-images.githubusercontent.com/36542986/200259080-5ffd5176-f965-4d25-bd3a-a5c99720eacc.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Said-laasri** [comment]
@TedLivist  thanks for reviewing our project

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your project is complete! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Fair distribution of tasks

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by digia3d** [comment]
Thank you for reviewing our project.:smiley:
